### ISSUE TITLE
Broken link in Arxiv article

### ISSUE THREAD

**Issue by impredicative** [Accla/D4M.py#3]
The abstract at https://arxiv.org/abs/2209.00602v1 has two HTTP links, both of which are broken. Can it be updated to fix them?

**Comment by haydenj** [comment]
Looks like arXiv automatically generates urls when it finds strings it thinks are urls (I had no idea until you brought it to my attention!). ".py" is the ccTLD for Paraguay, so it (incorrectly) converted them. arXiv technical support suggested making them LaTeX strings until a better site-wide solution exists, so it should at least be readable now.
